var peru =  [{
              image:"AnaPaulaVerme.jpg",
              name:"Ana"
            },{
              image:"JoselynInga.JPG",
              name:"Joselyn"
            },{
              image:"AntonellaGutierrez.jpg",
              name:"Antonella"
            },{
              image:"KarenValdivia.JPG",
              name:"Karen"
            },{
              image:"AstridCordova.jpg",
              name:"Astrid"
            },{
              image:"CarmenrosaArias.jpg",
              name:"Carmenrosa"
            },{
              image:"DanielaSegura.JPG",
              name:"Daniela"
            },{
              image:"DianaSantisteban.JPG",
              name:"Diana"
            },{
              image:"EmilyElenaVivanco.jpg",
              name:"Emily"
            },{
              image:"GabrielaSegura.jpg",
              name:"Gabriela"
            },{
              image:"GenesisLeon.jpg",
              name:"Genesis"
            },{
              image:"IngridDarianaPatiño.jpg",
              name:"Dariana"
            },{
              image:"JanetHuacahuasi.jpg",
              name:"Janet"
            },{
              image:"JennyVega.JPG",
              name:"Jenny"
            },{
              image:"JeseniaRodríguez.JPG",
              name:"Jesenia"
            },{
              image:"JohanaAzañero.JPG",
              name:"Johana"
            },{
              image:"JohelynCordova.JPG",
              name:"Johelyn"
            },{
              image:"PierinaAcevedo.JPG",
              name:"Pierina"
            },{
              image:"KarinaPrado.jpg",
              name:"Karina"
            },{
              image:"KarlaRios.jpg",
              name:"Karla"
            },{
              image:"KatherineLlacza.JPG",
              name:"Katherine"
            },{
              image:"KiaraEsquerra.JPG",
              name:"Kiara"
            },{
              image:"LisbethBalabarca.JPG",
              name:"Lisbeth"
            },{
              image:"LizethLopez.JPG",
              name:"Lizeth"
            },{
              image:"MagalyFlores.jpg",
              name:"Magaly"
            },{
              image:"MariaCeciliaLimay.JPG",
              name:"Cecilia"
            },{
              image:"MariaVictoriaCardenas.jpg",
              name:"Maria Victoria"
            },{
              image:"MerlinRupay.jpg",
              name:"Stefanny"
            },{
              image:"MiluRobles.JPG",
              name:"Milu"
            },{
              image:"MonicaCcencho.jpg",
              name:"Monica"
            },{
              image:"NayraPillihuaman.jpg",
              name:"Nayra"
            },{
              image:"PatriciaArakawa.JPG",
              name:"Patricia"
            },{
              image:"ReinaTorrejón.JPG",
              name:"Reina"
            },{
              image:"RitaOrtiz.jpg",
              name:"Rita"
            },{
              image:"SandraAzabache.JPG",
              name:"Sandra"
            },{
              image:"SaraNolasco.JPG",
              name:"Sara"
            },{
              image:"SaritaRoman.jpg",
              name:"Sarita"
            },{
              image:"TaniaCuya.JPG",
              name:"Tania"
            },{
              image:"VanessaAlvarado.jpg",
              name:"Vanessa"
            },{
              image:"VanessaVargas.JPG",
              name:"Vanessa"
            },{
              image:"VickensidelaCruz.jpg",
              name:"Vickensi"
            }];
